[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x555753"
blue = "0x729fcf"
cyan = "0x34e2e2"
green = "0x8ae234"
magenta = "0xad7fa8"
red = "0xef2929"
white = "0xeeeeec"
yellow = "0xfce94f"

[colors.normal]
black = "0x2e3436"
blue = "0x3465a4"
cyan = "0x06989a"
green = "0x4e9a06"
magenta = "0x75507b"
red = "0xcc0000"
white = "0xd3d7cf"
yellow = "0xc4a000"

[colors.primary]
background = "#1e1e1e"
foreground = "#d3d7cf"

[env]
TERM = "xterm-256color"

[font]
size = 12.5

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Book"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "K"
mode = "~Alt"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "J"
mode = "~Alt"
mods = "Shift|Control"

[[keyboard.bindings]]
action = "ScrollToTop"
key = "Home"
mode = "~Alt"

[[keyboard.bindings]]
action = "ScrollToBottom"
key = "End"
mode = "~Alt"

[scrolling]
history = 10000
multiplier = 3

[window.dimensions]
columns = 90
lines = 18
